# Generated by Django 5.0.1 on 2024-01-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
