# Generated by Django 5.0.1 on 2024-01-08 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0002_movie_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
